---
base_url: 'https://www.meteoschweiz.admin.ch/product/input/radio-soundings/'
storage_file: station_data.pickle
stations:
  - name: payerne
    code: VSST76
  - name: stuttgart
    code: VSST78
  - name: munich
    code: VSST77
  - name: milano
    code: VSST80



